CREATE TABLE [edfiV3].[Course] (
    [ApiSchoolYear]	   SMALLINT NOT NULL, 
	[CourseCode]                             NVARCHAR (60)    NOT NULL,
    [EducationOrganizationId]                INT              NOT NULL,
    [CourseTitle]                            NVARCHAR (100)    NOT NULL,
    [NumberOfParts]                          INT              NOT NULL,
    [AcademicSubjectDescriptorId]            INT              NULL,
    [CourseDescription]                      NVARCHAR (1024)  NULL,
    [TimeRequiredForCompletion]              INT              NULL,
    [DateCourseAdopted]                      DATE             NULL,
    [HighSchoolCourseRequirement]            BIT              NULL,
    [CourseGPAApplicabilityDescriptorId]     INT              NULL,
    [CourseDefinedByDescriptorId]            INT              NULL,
    [MinimumAvailableCredits]                DECIMAL (9, 3)   NULL,
    [MinimumAvailableCreditTypeDescriptorId] INT              NULL,
    [MinimumAvailableCreditConversion]       DECIMAL (9, 2)   NULL,
    [MaximumAvailableCredits]                DECIMAL (9, 3)   NULL,
    [MaximumAvailableCreditTypeDescriptorId] INT              NULL,
    [MaximumAvailableCreditConversion]       DECIMAL (9, 2)   NULL,
    [CareerPathwayDescriptorId]              INT              NULL,
    [MaxCompletionsForCredit]                INT              NULL,
    [CreateDate]							 DATETIME2 (7)         NOT NULL,
    [LastModifiedDate]						 DATETIME2 (7)         NOT NULL,
    [Id]									 UNIQUEIDENTIFIER NOT NULL,
	[IsActive] BIT CONSTRAINT [V3_Course_DF_IsActive] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [V3_Course_PK] PRIMARY KEY CLUSTERED ([ApiSchoolYear] ASC, [CourseCode] ASC, [EducationOrganizationId] ASC),
    CONSTRAINT [V3_FK_Course_AcademicSubjectDescriptor] FOREIGN KEY ([AcademicSubjectDescriptorId]) REFERENCES [edfiV3].[AcademicSubjectDescriptor] ([AcademicSubjectDescriptorId]),
    --CONSTRAINT [V3_FK_Course_CareerPathwayDescriptor] FOREIGN KEY ([CareerPathwayDescriptorId]) REFERENCES [edfiV3].[CareerPathwayDescriptor] ([CareerPathwayDescriptorId]),
    --CONSTRAINT [V3_FK_Course_CourseDefinedByDescriptor] FOREIGN KEY ([CourseDefinedByDescriptorId]) REFERENCES [edfiV3].[CourseDefinedByDescriptor] ([CourseDefinedByDescriptorId]),
    --CONSTRAINT [V3_FK_Course_CourseGPAApplicabilityDescriptor] FOREIGN KEY ([CourseGPAApplicabilityDescriptorId]) REFERENCES [edfiV3].[CourseGPAApplicabilityDescriptor] ([CourseGPAApplicabilityDescriptorId]),
    --CONSTRAINT [V3_FK_Course_CreditTypeDescriptor] FOREIGN KEY ([MinimumAvailableCreditTypeDescriptorId]) REFERENCES [edfiV3].[CreditTypeDescriptor] ([CreditTypeDescriptorId]),
	--CONSTRAINT [V3_FK_Course_CreditTypeDescriptor1] FOREIGN KEY ([MaximumAvailableCreditTypeDescriptorId]) REFERENCES [edfiV3].[CreditTypeDescriptor] ([CreditTypeDescriptorId]),
    CONSTRAINT [V3_FK_Course_EducationOrganization] FOREIGN KEY ([ApiSchoolYear], [EducationOrganizationId]) REFERENCES [edfiV3].[EducationOrganization] ([ApiSchoolYear], [EducationOrganizationId])
);
