CREATE TABLE [edfiV3].[Grade] (
    [ApiSchoolYear]	   SMALLINT NOT NULL,
	[BeginDate]                             DATE             NOT NULL,
    [GradeTypeDescriptorId]                 INT              NOT NULL,
    [GradingPeriodDescriptorId]             INT              NOT NULL,
    [GradingPeriodSchoolYear]               SMALLINT         NOT NULL,
    [GradingPeriodSequence]                 INT              NOT NULL,
    [LocalCourseCode]                       NVARCHAR (60)    NOT NULL,
    [SchoolId]                              INT              NOT NULL,
    [SchoolYear]                            SMALLINT         NOT NULL,
    [SectionIdentifier]                     NVARCHAR (255)   NOT NULL,
    [SessionName]                           NVARCHAR (60)    NOT NULL,
    [StudentUSI]                            INT              NOT NULL,
    [LetterGradeEarned]                     NVARCHAR (20)    NULL,
    [NumericGradeEarned]                    DECIMAL (9, 2)   NULL,
    [DiagnosticStatement]                   NVARCHAR (1024)  NULL,
    [PerformanceBaseConversionDescriptorId] INT              NULL,
    [CreateDate]                            DATETIME2 (7)         NOT NULL,
    [LastModifiedDate]                      DATETIME2 (7)         NOT NULL,
    [Id]                                    UNIQUEIDENTIFIER NOT NULL,
	[IsActive] BIT CONSTRAINT [V3_Grade_DF_IsActive] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [V3_Grade_PK] PRIMARY KEY CLUSTERED ([ApiSchoolYear] ASC, [SchoolId] ASC, [StudentUSI] ASC, [BeginDate] ASC, [GradeTypeDescriptorId] ASC, [GradingPeriodDescriptorId] ASC, [GradingPeriodSchoolYear] ASC, [GradingPeriodSequence] ASC, [LocalCourseCode] ASC, [SchoolYear] ASC,[SectionIdentifier] ASC, [SessionName] ASC),
    CONSTRAINT [V3_FK_Grade_GradeTypeDescriptor] FOREIGN KEY ([GradeTypeDescriptorId]) REFERENCES [edfiV3].[GradeTypeDescriptor] ([GradeTypeDescriptorId]),
    CONSTRAINT [V3_FK_Grade_GradingPeriod] FOREIGN KEY ([ApiSchoolYear], [SchoolId],[GradingPeriodSchoolYear],  [GradingPeriodDescriptorId], [GradingPeriodSequence]) REFERENCES [edfiV3].[GradingPeriod] ([ApiSchoolYear], [SchoolId], [SchoolYear], [GradingPeriodDescriptorId], [PeriodSequence]),
    CONSTRAINT [V3_FK_Grade_PerformanceBaseConversionDescriptor] FOREIGN KEY ([PerformanceBaseConversionDescriptorId]) REFERENCES [edfiV3].[PerformanceBaseConversionDescriptor] ([PerformanceBaseConversionDescriptorId]),
    CONSTRAINT [V3_FK_Grade_StudentSectionAssociation] FOREIGN KEY ([ApiSchoolYear], [SchoolId], [SchoolYear], [StudentUSI], [BeginDate], [LocalCourseCode], [SectionIdentifier], [SessionName]) REFERENCES [edfiV3].[StudentSectionAssociation] ([ApiSchoolYear], [SchoolId], [SchoolYear], [StudentUSI], [BeginDate], [LocalCourseCode] , [SectionIdentifier], [SessionName]) ON UPDATE CASCADE
);
