CREATE TABLE [edfiV3].[StudentAcademicRecord] (
    [ApiSchoolYear]	   SMALLINT NOT NULL,
	[EducationOrganizationId]                   INT              NOT NULL,
    [SchoolYear]                                SMALLINT         NOT NULL,
    [StudentUSI]                                INT              NOT NULL,
    [TermDescriptorId]                          INT              NOT NULL,
    [CumulativeEarnedCredits]                   DECIMAL (9, 3)   NULL,
    [CumulativeEarnedCreditTypeDescriptorId]    INT              NULL,
    [CumulativeEarnedCreditConversion]          DECIMAL (9, 2)   NULL,
    [CumulativeAttemptedCredits]                DECIMAL (9, 3)   NULL,
    [CumulativeAttemptedCreditTypeDescriptorId] INT              NULL,
    [CumulativeAttemptedCreditConversion]       DECIMAL (9, 2)   NULL,
    [CumulativeGradePointsEarned]               DECIMAL (18, 4)  NULL,
    [CumulativeGradePointAverage]               DECIMAL (18, 4)  NULL,
    [GradeValueQualifier]                       NVARCHAR (80)    NULL,
    [ProjectedGraduationDate]                   DATE             NULL,
    [SessionEarnedCredits]                      DECIMAL (9, 3)   NULL,
    [SessionEarnedCreditTypeDescriptorId]       INT              NULL,
    [SessionEarnedCreditConversion]             DECIMAL (9, 2)   NULL,
    [SessionAttemptedCredits]                   DECIMAL (9, 3)   NULL,
    [SessionAttemptedCreditTypeDescriptorId]    INT              NULL,
    [SessionAttemptedCreditConversion]          DECIMAL (9, 2)   NULL,
    [SessionGradePointsEarned]                  DECIMAL (18, 4)  NULL,
    [SessionGradePointAverage]                  DECIMAL (18, 4)  NULL,
    [CreateDate]                                DATETIME2 (7)         NOT NULL,
    [LastModifiedDate]                          DATETIME2 (7)         NOT NULL,
    [Id]                                        UNIQUEIDENTIFIER NOT NULL,
	[IsActive]									BIT			CONSTRAINT [V3_StudentAcademicRecord_IsActive] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [V3_StudentAcademicRecord_PK] PRIMARY KEY CLUSTERED ([ApiSchoolYear] ASC, [EducationOrganizationId] ASC, [SchoolYear] ASC,  [StudentUSI] ASC, [TermDescriptorId] ASC),
    --CONSTRAINT [FK_StudentAcademicRecord_CreditTypeDescriptor] FOREIGN KEY ([CumulativeEarnedCreditTypeDescriptorId]) REFERENCES [edfi].[CreditTypeDescriptor] ([CreditTypeDescriptorId]),
    --CONSTRAINT [FK_StudentAcademicRecord_CreditTypeDescriptor1] FOREIGN KEY ([CumulativeAttemptedCreditTypeDescriptorId]) REFERENCES [edfi].[CreditTypeDescriptor] ([CreditTypeDescriptorId]),
    --CONSTRAINT [FK_StudentAcademicRecord_CreditTypeDescriptor2] FOREIGN KEY ([SessionEarnedCreditTypeDescriptorId]) REFERENCES [edfi].[CreditTypeDescriptor] ([CreditTypeDescriptorId]),
    --CONSTRAINT [FK_StudentAcademicRecord_CreditTypeDescriptor3] FOREIGN KEY ([SessionAttemptedCreditTypeDescriptorId]) REFERENCES [edfi].[CreditTypeDescriptor] ([CreditTypeDescriptorId]),
    CONSTRAINT [V3_FK_StudentAcademicRecord_EducationOrganization] FOREIGN KEY ([ApiSchoolYear], [EducationOrganizationId]) REFERENCES [edfiV3].[EducationOrganization] ([ApiSchoolYear], [EducationOrganizationId]),
    CONSTRAINT [V3_FK_StudentAcademicRecord_SchoolYearType] FOREIGN KEY ([SchoolYear]) REFERENCES [edfiV3].[SchoolYearType] ([SchoolYear]),
    CONSTRAINT [V3_FK_StudentAcademicRecord_Student] FOREIGN KEY ([ApiSchoolYear], [StudentUSI]) REFERENCES [edfiV3].[Student] ([ApiSchoolYear], [StudentUSI]),
    CONSTRAINT [V3_FK_StudentAcademicRecord_TermDescriptor] FOREIGN KEY ([TermDescriptorId]) REFERENCES [edfiV3].[TermDescriptor] ([TermDescriptorId])
);
