CREATE TABLE [edfiV3].[Section] (
    [ApiSchoolYear]	   SMALLINT NOT NULL,
	[LocalCourseCode]                     NVARCHAR (60)    NOT NULL,
    [SchoolId]                            INT              NOT NULL,
    [SchoolYear]                          SMALLINT         NOT NULL,
    [SectionIdentifier]                   NVARCHAR (255)   NOT NULL,
    [SessionName]                         NVARCHAR (60)    NOT NULL,
    [SequenceOfCourse]                    INT              NULL,
    [EducationalEnvironmentDescriptorId]  INT              NULL,
    [MediumOfInstructionDescriptorId]     INT              NULL,
    [PopulationServedDescriptorId]        INT              NULL,
    [AvailableCredits]                    DECIMAL (9, 3)   NULL,
    [AvailableCreditTypeDescriptorId]     INT              NULL,
    [AvailableCreditConversion]           DECIMAL (9, 2)   NULL,
    [InstructionLanguageDescriptorId]     INT              NULL,
    [LocationSchoolId]                    INT              NULL,
    [LocationClassroomIdentificationCode] NVARCHAR (60)    NULL,
    [CreateDate]                          DATETIME2 (7)         NOT NULL,
    [LastModifiedDate]                    DATETIME2 (7)         NOT NULL,
    [Id]                                  UNIQUEIDENTIFIER NOT NULL,
	[IsActive] BIT CONSTRAINT [V3_Section_DF_IsActive] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [V3_Section_PK] PRIMARY KEY CLUSTERED ([ApiSchoolYear] ASC,[SchoolId] ASC, [SchoolYear] ASC, [LocalCourseCode] ASC, [SectionIdentifier] ASC, [SessionName] ASC),
    CONSTRAINT [V3_FK_Section_CourseOffering] FOREIGN KEY ([ApiSchoolYear], [SchoolId], [SchoolYear],[LocalCourseCode], [SessionName]) REFERENCES [edfiV3].[CourseOffering] ([ApiSchoolYear], [SchoolId],  [SchoolYear], [LocalCourseCode], [SessionName]),
    --CONSTRAINT [V3_FK_Section_CreditTypeDescriptor] FOREIGN KEY ([AvailableCreditTypeDescriptorId]) REFERENCES [edfiV3].[CreditTypeDescriptor] ([CreditTypeDescriptorId]),
    --CONSTRAINT [V3_FK_Section_EducationalEnvironmentDescriptor] FOREIGN KEY ([EducationalEnvironmentDescriptorId]) REFERENCES [edfiV3].[EducationalEnvironmentDescriptor] ([EducationalEnvironmentDescriptorId]),
    --CONSTRAINT [V3_FK_Section_LanguageDescriptor] FOREIGN KEY ([InstructionLanguageDescriptorId]) REFERENCES [edfiV3].[LanguageDescriptor] ([LanguageDescriptorId]),
    CONSTRAINT [V3_FK_Section_Location] FOREIGN KEY ([ApiSchoolYear], [LocationSchoolId], [LocationClassroomIdentificationCode]) REFERENCES [edfiV3].[Location] ([ApiSchoolYear], [SchoolId], [ClassroomIdentificationCode]) ON UPDATE CASCADE,
    CONSTRAINT [V3_FK_Section_MediumOfInstructionDescriptor] FOREIGN KEY ([MediumOfInstructionDescriptorId]) REFERENCES [edfiV3].[MediumOfInstructionDescriptor] ([MediumOfInstructionDescriptorId]),
    --CONSTRAINT [V3_FK_Section_PopulationServedDescriptor] FOREIGN KEY ([PopulationServedDescriptorId]) REFERENCES [edfiV3].[PopulationServedDescriptor] ([PopulationServedDescriptorId]),
    CONSTRAINT [V3_FK_Section_School] FOREIGN KEY ([ApiSchoolYear], [LocationSchoolId]) REFERENCES [edfiV3].[School] ([ApiSchoolYear], [SchoolId])
);
