CREATE TABLE [edfiV3].[StudentSpecialEducationProgramAssociation] (
	[ApiSchoolYear]	   SMALLINT NOT NULL,
    [BeginDate]                           DATE           NOT NULL,
    [EducationOrganizationId]             INT            NOT NULL,
    [ProgramEducationOrganizationId]      INT            NOT NULL,
    [ProgramName]                         NVARCHAR (60)  NOT NULL,
    [ProgramTypeDescriptorId]             INT            NOT NULL,
    [StudentUSI]                          INT            NOT NULL,
    [IdeaEligibility]                     BIT            NULL,
    [SpecialEducationSettingDescriptorId] INT            NULL,
    [SpecialEducationHoursPerWeek]        DECIMAL (5, 2) NULL,
    [SchoolHoursPerWeek]                  DECIMAL (5, 2) NULL,
    [MultiplyDisabled]                    BIT            NULL,
    [MedicallyFragile]                    BIT            NULL,
    [LastEvaluationDate]                  DATE           NULL,
    [IEPReviewDate]                       DATE           NULL,
    [IEPBeginDate]                        DATE           NULL,
    [IEPEndDate]                          DATE           NULL,
    [DpiReportingDisability]                    VARCHAR (3)      NULL,
    [DpiCalcDateModified]						DATETIME         NULL,
	CONSTRAINT [V3_StudentSpecialEducationProgramAssociation_PK] PRIMARY KEY CLUSTERED ([ApiSchoolYear] Asc, [EducationOrganizationId] ASC, [StudentUSI] ASC, [BeginDate] ASC, [ProgramEducationOrganizationId] ASC, [ProgramName] ASC, [ProgramTypeDescriptorId] ASC),
    CONSTRAINT [V3_FK_StudentSpecialEducationProgramAssociation_GeneralStudentProgramAssociation] FOREIGN KEY ([ApiSchoolYear], [EducationOrganizationId], [StudentUSI], [BeginDate], [ProgramEducationOrganizationId], [ProgramName], [ProgramTypeDescriptorId]) REFERENCES [edfiV3].[GeneralStudentProgramAssociation] ([ApiSchoolYear], [EducationOrganizationId], [StudentUSI], [BeginDate], [ProgramEducationOrganizationId], [ProgramName], [ProgramTypeDescriptorId]) ON DELETE CASCADE,
    CONSTRAINT [V3_FK_StudentSpecialEducationProgramAssociation_SpecialEducationSettingDescriptor] FOREIGN KEY ([SpecialEducationSettingDescriptorId]) REFERENCES [edfiV3].[SpecialEducationSettingDescriptor] ([SpecialEducationSettingDescriptorId])
);

