CREATE TABLE [edfiV3].[StudentSectionAssociation] (
    [ApiSchoolYear]	   SMALLINT NOT NULL,
    [BeginDate]                       DATE             NOT NULL,
    [LocalCourseCode]                 NVARCHAR (60)    NOT NULL,
    [SchoolId]                        INT              NOT NULL,
    [SchoolYear]                      SMALLINT         NOT NULL,
    [SectionIdentifier]               NVARCHAR (255)   NOT NULL,
    [SessionName]                     NVARCHAR (60)    NOT NULL,
    [StudentUSI]                      INT              NOT NULL,
    [EndDate]                         DATE             NULL,
    [HomeroomIndicator]               BIT              NULL,
    [RepeatIdentifierDescriptorId]    INT              NULL,
    [TeacherStudentDataLinkExclusion] BIT              NULL,
    [AttemptStatusDescriptorId]       INT              NULL,
    [CreateDate]                      DATETIME2 (7)         NOT NULL,
    [LastModifiedDate]                DATETIME2 (7)         NOT NULL,
    [Id]                              UNIQUEIDENTIFIER NOT NULL,
	[IsActive] BIT CONSTRAINT [V3_StudentSectionAssociation_DF_IsActive] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [V3_StudentSectionAssociation_PK] PRIMARY KEY CLUSTERED ([ApiSchoolYear] ASC, [SchoolId] ASC, [SchoolYear] ASC, [StudentUSI] ASC, [BeginDate] ASC, [LocalCourseCode] ASC, [SectionIdentifier] ASC, [SessionName] ASC),
    CONSTRAINT [V3_FK_StudentSectionAssociation_AttemptStatusDescriptor] FOREIGN KEY ([AttemptStatusDescriptorId]) REFERENCES [edfiV3].[AttemptStatusDescriptor] ([AttemptStatusDescriptorId]),
    --CONSTRAINT [V3_FK_StudentSectionAssociation_RepeatIdentifierDescriptor] FOREIGN KEY ([RepeatIdentifierDescriptorId]) REFERENCES [edfiV3].[RepeatIdentifierDescriptor] ([RepeatIdentifierDescriptorId]),
    CONSTRAINT [V3_FK_StudentSectionAssociation_Section] FOREIGN KEY ([ApiSchoolYear], [SchoolId], [SchoolYear], [LocalCourseCode], [SectionIdentifier], [SessionName]) REFERENCES [edfiV3].[Section] ([ApiSchoolYear], [SchoolId], [SchoolYear], [LocalCourseCode], [SectionIdentifier], [SessionName]) ON UPDATE CASCADE,
    CONSTRAINT [V3_FK_StudentSectionAssociation_Student] FOREIGN KEY ([ApiSchoolYear], [StudentUSI]) REFERENCES [edfiV3].[Student] ([ApiSchoolYear], [StudentUSI])
);
