CREATE TABLE [ace].[MembershipIntervalArchive] (
    [MembershipIntervalId]									BIGINT          NOT NULL,
    [ExecutionId]											INT             NOT NULL,
    [FiscalYear]											INT             NOT NULL,
    [ADMTypeId]												INT             NOT NULL,
    [AggregationTypeId]										INT             NOT NULL,
    [ReportingPeriodTypeId]									INT             NOT NULL,
    [ReportingPeriodId]										INT             NOT NULL,
    [StudentUSI]											INT             NOT NULL,
    [SchoolId]												INT             NOT NULL,
    [GradeLevelTypeId]										INT             NOT NULL,
    [AttendingLocalEducationAgencyId]						INT             NOT NULL,
    [ResidentEducationOrganizationId]						INT             NOT NULL,
    [IsConcurrentForLimiting]								SMALLINT		NOT NULL,
    [MembershipFTEDescriptorId]								INT             NOT NULL,
    [TuitionPayerDescriptorId]								INT             NOT NULL,
    [ProgramServiceDescriptorId]							INT             NULL,
    [TrackNumber]											INT             NULL,
    [IsHomeBound]											BIT             NOT NULL,
    [FundingTypeId]											INT             NOT NULL,
    [MembershipIntervalStartDate]							DATE            NOT NULL,
    [MembershipIntervalEndDate]								DATE            NOT NULL,
    [UnadjustedMembershipDays]								DECIMAL (10, 6) NOT NULL,
    [UnadjustedAbsenceDays]									DECIMAL (10, 6) NULL,
    [UnadjustedAverageDailyMembership]						DECIMAL (10, 4) NOT NULL,
    [UnadjustedAverageDailyAttendance]						DECIMAL (10, 4) NULL,
    [CreateDate]											DATETIME        NOT NULL,
    [SPEDSupportLevelWeight]								DECIMAL(10, 4)	NULL, 
	[SpecialEnrollmentDescriptorId]							INT				NULL,
	[ServiceCodeDescriptorId]								INT				NULL,
	[StudentSchoolAssociationEntryDate]						DATE			NOT NULL,
    [UnadjustedDaysEnrolled]								DECIMAL (10, 6) NOT NULL, 
    [YearEndUnadjustedADM]									DECIMAL (10, 4) NOT NULL, 
    [YearEndAdjustedADM]									DECIMAL (10, 4) NOT NULL, 
    [YearEndAdjustedADA]									DECIMAL (10, 4) NOT NULL, 
	[LimitedAverageDailyMembership]							DECIMAL (10, 4) NOT NULL,
	[LimitedAverageDailyAttendance]							DECIMAL (10, 4) NOT NULL,
	[LimitedMembershipDays]									DECIMAL (10, 6) NOT NULL,
	[LimitedAbsenceDays]									DECIMAL (10, 6) NOT NULL,
	[AttendanceMinutes]										DECIMAL (10, 4) NULL,
    CONSTRAINT [PK_MembershipIntervalArchive] PRIMARY KEY CLUSTERED ([MembershipIntervalId] ASC),
);

GO

