CREATE TYPE [ace].[MembershipIntervalTableType] AS TABLE(
	[ExecutionId] [int] NOT NULL,
	[FiscalYear] [int] NOT NULL,
	[ADMTypeId] [int] NOT NULL,
	[AggregationTypeId] [int] NOT NULL,
	[ReportingPeriodTypeId] [int] NOT NULL,
	[ReportingPeriodId] [int] NOT NULL,
	[StudentUSI] [int] NOT NULL,
	[SchoolId] [int] NOT NULL,
	[GradeLevelTypeId] [int] NOT NULL,
	[AttendingLocalEducationAgencyId] [int] NOT NULL,
	[ResidentEducationOrganizationId] [int] NOT NULL,
	[IsConcurrentForLimiting] [char](1) NOT NULL,
	[MembershipFTEDescriptorId] [int] NOT NULL,
	[TuitionPayerDescriptorId] [int] NOT NULL,
	[ProgramServiceDescriptorId] [int] NULL,
	[TrackNumber] [int] NULL,
	[CalendarCode] [NVarchar](60) NULL,
	[IsHomeBound] [bit] NOT NULL,
	[FundingTypeId] [int] NOT NULL,
	[MembershipIntervalStartDate] [date] NOT NULL,
	[MembershipIntervalEndDate] [date] NOT NULL,
	[UnadjustedMembershipDays] [decimal](10, 6) NULL,
	[UnadjustedAbsenceDays] [decimal](10, 6) NULL,
	[UnadjustedAverageDailyMembership] [decimal](10, 4) NULL,
	[UnadjustedAverageDailyAttendance] [decimal](10, 4) NULL,
	[CreateDate] [datetime] NOT NULL,
	[SPEDSupportLevelWeight] [decimal](10, 6) NULL,
	[SpecialEnrollmentDescriptorId] [int] NULL,
	[ServiceCodeDescriptorId] [int] NULL,	
	[StudentSchoolAssociationEntryDate] [date] NOT NULL,
	[UnadjustedDaysEnrolled] [decimal](10, 6) NOT NULL,
	[YearEndUnadjustedADM] [decimal](10, 4) NOT NULL,
	[YearEndAdjustedADM] [decimal](10, 4) NOT NULL,
    [YearEndAdjustedADA] [decimal] (10, 4) NOT NULL, 
	[LimitedAverageDailyMembership] [decimal](10, 4) NOT NULL,
	[LimitedAverageDailyAttendance] [decimal](10, 4) NOT NULL,
	[LimitedMembershipDays] [decimal] (10, 6) NOT NULL,
	[LimitedAbsenceDays] [decimal] (10, 6) NOT NULL,
	[AttendanceMinutes] [decimal] (10, 4) NULL,
	[SubmittedByEducationOrganizationId] [int] NULL,
	IsChronicallyIll [bit] NULL
)
GO