
CREATE TABLE [config].[Filetype915](
	[Filetype915Id] [int] NOT NULL,
	[Filetype915Description] [varchar](50) NOT NULL,
 CONSTRAINT [PK_915Filetype] PRIMARY KEY CLUSTERED 
(
	[Filetype915Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


