CREATE TABLE [config].[GradDateThreshold](
	[FiscalYear] [int] NOT NULL,
	[ThresholdDays] [int] NOT NULL,
 CONSTRAINT [PK_GradDateThreshold] PRIMARY KEY CLUSTERED 
(
	[FiscalYear] ASC,
	[ThresholdDays] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
