
CREATE TABLE [config].[RequestType915](
	[RequestTypeId] [int] NOT NULL,
	[RequestTypeDescription] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Config.RequestType915] PRIMARY KEY CLUSTERED 
(
	[RequestTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

